name: CI Angular

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci-angular:
    name: Angular CI (Node ${{ matrix.node-version }})
    strategy:
      fail-fast: false
      matrix:
        node-version: ["18", "20"]
    uses: TP-meditrack-SS-Org/shared-workflow-ci/.github/workflows/ci-express.yml@5c2cb1f04439c45e94b9fa1ed4252bd3cec3cad2 # chore/supply-chain-hardening
    with:
      node-version: ${{ matrix.node-version }}
      test-command: npm run test:ci
